server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true

  main:
    allow-bean-definition-overriding: true


security:
  oauth2:
    jwt:
      signkey: 123@#$

oauth2-config:
  client:
    id: testClient
    secret: testSecret
    scope: read,write
  grant-types:
    - authorization_code
    - refresh_token
  redirect_url: "http://localhost:8081/oauth/callback"

